services:
  mysql:
    image: mysql:8
    container_name: skillhub-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skillhub
      MYSQL_USER: skillhub
      MYSQL_PASSWORD: skillhub
      TZ: Europe/Madrid
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: skillhub-adminer
    restart: unless-stopped
    ports:
      - "8082:8080"   # Adminer UI en http://localhost:8082
    environment:
      - TZ=Europe/Madrid

volumes:
  mysql_data:
